twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes: ['Form/fields.html.twig']
  globals:
    locales: '%supported_locales%'
  file_name_pattern: '*.twig'

when@test:
  twig:
    strict_variables: true
