language: php
sudo: false

php:
  - '7.1'
  - '7.2'

env:
  global:
    - DATABASE_DRIVER=pdo_mysql
    - DATABASE_URL=mysql://mail_test:password@127.0.0.1:3306/mail_test
    - APP_ENV=test
    - APP_SECRET=165e25e3846534bb4665d7078a851c0b
    - MAILER_URL=smtp://localhost:25?encryption=&auth_mode=
    - MAILER_DELIVERY_ADDRESS=admin@example.org
    - APP_NAME="User Management"
    - APP_URL="https://users.example.org/"
    - PROJECT_NAME="example.org"
    - PROJECT_URL="https://www.example.org/"
    - DOMAIN="example.org"
    - SENDER_ADDRESS="admin@example.org"
    - NOTIFICATION_ADDRESS="monitoring@example.org"
    - SEND_MAIL="true"
    - LOCALE="de"
    - HAS_SINA_BOX="false"

cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - mysql
  - postgresql

before_install:
  - mysql -e 'CREATE DATABASE mail_test;'
  - mysql -e "CREATE USER 'mail_test'@'localhost' IDENTIFIED BY 'password';"
  - mysql -e "GRANT ALL PRIVILEGES on mail_test.* to mail_test@localhost;"
  - sudo -u postgres createuser -d mail_test
  - sudo -u postgres createdb -O mail_test mail_test
  - sudo apt-get install openssl
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/ondrej-php-trusty.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
  - sudo apt-get install -y libsodium-dev

install:
  - printf "\n" | pecl install libsodium-2.0.13
  - composer install

jobs:
  include:
    - script: make integration
      name: Integration with sqlite
      env:
        - DATABASE_DRIVER=pdo_sqlite
        - DATABASE_URL=sqlite:///%kernel.project_dir%/var/db_test.sqlite

    - script: make integration
      name: Integration with MySQL
      if: branch = master
      env:
        - DATABASE_DRIVER=pdo_mysql
        - DATABASE_URL=mysql://mail_test:password@127.0.0.1:3306/mail_test

    - script: make integration
      name: Integration with PostgreSQL
      if: branch = master
      env:
        - DATABASE_DRIVER=pdo_pgsql
        - DATABASE_URL=pgsql://mail_test:password@127.0.0.1:5432/mail_test
