---
site_name: Userli
site_author: Systemli
repo_url: https://github.com/systemli/userli

nav:
  - Home: index.md
  - Development:
      - "Getting started": development/index.md
      - "Code of Conduct": development/code_of_conduct.md
      - "Coding style": development/coding_style.md
      - Logs: development/logs.md
      - Icons: development/icons.md
      - Release: development/release.md
      - Tests: development/tests.md
  - Installation:
      - Installation: installation/index.md
      - Code: installation/code.md
      - Commands: installation/commands.md
      - Configuration: installation/configuration.md
      - Customize: installation/customize.md
      - Database: installation/database.md
      - Dovecot: installation/dovecot.md
      - Finalize: installation/finalize.md
      - Webserver: installation/webserver.md
  - Update: update/index.md
  - Features:
      - MailCrypt: features/mail_crypt.md
      - MTA-STS: features/mta-sts.md
      - "Web Key Directory": features/wkd.md
      - Integrations: features/integrations.md
      - Webhooks: features/webhooks.md
  - Screenshots: screenshots/index.md

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    primary: "blue"
    accent: "blue"

extra:
  generator: false
  social:
    - icon: fontawesome/solid/globe
      link: https://www.systemli.org
    - icon: fontawesome/brands/github
      link: https://github.com/systemli

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

