settings:
  app_name:
    type: string
    default: "Userli"
    validation:
      min_length: 3
      max_length: 30

  app_url:
    type: url
    default: "https://users.example.org"

  project_name:
    type: string
    default: "example.org"

  project_url:
    type: url
    default: "https://www.example.org"

  email_sender_address:
    type: email
    default: "admin@example.org"

  email_notification_address:
    type: email
    default: "monitoring@example.org"

  webmail_url:
    type: url
    default: ""
    optional: true

  weekly_report_enabled:
    type: boolean
    default: true

  smtp_quota_limit_per_hour:
    type: integer
    default: 0
    validation:
      min: 0

  smtp_quota_limit_per_day:
    type: integer
    default: 0
    validation:
      min: 0

  mta_sts_mode:
    type: string
    default: "testing"
    validation:
      choices: ["none", "testing", "enforce"]

  mta_sts_mx:
    type: textarea
    default: ""
    optional: true

  mta_sts_max_age:
    type: integer
    default: 604800
    validation:
      min: 86400
      max: 31557600
