name: Composer Update

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-24.04
    name: Update Composer Dependencies
    steps:
      - name: Obtain Access Token
        id: access_token
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.SYSTEMLI_APP_CREDENTIALS_TOKEN }})"
          echo "::add-mask::$TOKEN"
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2
        with:
          php-version: "8.4"
          extensions: openssl, sodium
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Update dependencies
        run: composer update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
        with:
          token: ${{ steps.access_token.outputs.token }}
          commit-message: "⬆️ Update composer dependencies"
          branch: automated/composer-update
          title: "⬆️ Update composer dependencies"
          body: |
            Automated `composer update` with Symfony Flex.
            Respects `extra.symfony.require` from `composer.json`.
          draft: true
