name: test-mailcrypt

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-mailcrypt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Build Stack
        run: docker compose build
      - name: Load fixtures
        run: |
          docker compose exec userli bin/console doctrine:fixtures:load --group=basic --no-interaction
      - name: Test mailcrypt
        run: |
          docker compose exec dovecot /tests/test_mailcrypt.sh
      - name: Shutdown
        if: always()
        run: docker compose down
